name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.24.1'
      - run: git config user.email "a.maniquiz@yahoo.com"
      - run: git config user.name "Anthony P. Maniquiz"
      - name: Run npm install
        run: npm install
      - name: Run the gh-pages build
        run: npm run deploy
      # - name: Run the build for deployment bundling
      #   run: npm run build
